sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: jms20041105

  redis:
    host: localhost
    port: 6379
    database: 10

  wechat:
    appid:
    secret:
    mchid:
    mch-serial-no:
    api-v3-key:
    notify-url:
    refund-notify-url:
    private-key-file-path:
    we-chat-pay-cert-file-path: